<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class General_setting extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('General_setting_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'general_setting/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'general_setting/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'general_setting/index.html';
            $config['first_url'] = base_url() . 'general_setting/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->General_setting_model->total_rows($q);
        $general_setting = $this->General_setting_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'general_setting_data' => $general_setting,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('general_setting/general_setting_list', $data);
    }

    public function read($id) 
    {
        $row = $this->General_setting_model->get_by_id($id);
        if ($row) {
            $data = array(
			'id' => $row->id,
			'record_duration' => $row->record_duration,
	    );
            $this->load->view('general_setting/general_setting_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('general_setting'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('general_setting/create_action'),
	    'id' => set_value('id'),
	    'record_duration' => set_value('record_duration'),
	);
        $this->load->view('general_setting/general_setting_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
			'record_duration' => $this->input->post('record_duration',TRUE),
	    );

            $this->General_setting_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('general_setting'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->General_setting_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('general_setting/update_action'),
			'id' => set_value('id', $row->id),
			'record_duration' => set_value('record_duration', $row->record_duration),
	    );
            $this->load->view('general_setting/general_setting_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('general_setting'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
			'record_duration' => $this->input->post('record_duration',TRUE),
	    );

            $this->General_setting_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('general_setting'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->General_setting_model->get_by_id($id);

        if ($row) {
            $this->General_setting_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('general_setting'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('general_setting'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('record_duration', 'record duration', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file General_setting.php */
/* Location: ./application/controllers/General_setting.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-09-23 03:01:23 */
/* http://harviacode.com */